import fs from 'node:fs';
import path from 'node:path';

const base = 'https://islamicwillscanada.pages.dev';
const out = path.resolve('dist');
const links = {
  templateFolder: 'https://drive.google.com/drive/folders/1N0zo57fszkn5195a-6I25_5mt3kfwmSw',
  windsor: 'https://drive.google.com/open?id=1dda59Ce2HcNm8Cp1ZHMrlQ_wZZnChfPO',
  filled: 'https://drive.google.com/open?id=1Vwj6NDJ6nMbq89ueoKejnr-2GrOw5-Cz',
  lawyerAnswers: 'https://drive.google.com/open?id=1PE3erzaGWj-_5uBV9vxHFMBAl5VZg5hx',
  seminarUrdu: 'https://www.youtube.com/watch?v=JzsemfNEIFc',
  seminarEnglish: 'https://www.youtube.com/watch?v=sZwS1YmplEI',
  workshop: 'https://www.youtube.com/watch?v=IFDi-fKzaLg',
  slidesUrdu: 'https://drive.google.com/open?id=1xabzczXbEi07oWbGJryYbMR1dJr97Q1F',
  slidesEnglish: 'https://drive.google.com/open?id=1YHPcALQO0JXmFEYr2M0-WGWm9g2KHHSq',
  workshopFolder: 'https://drive.google.com/drive/folders/1WHAfG4YU5GOTGI3C6xzqfhwdtgoRi2PR',
  knowledge: 'https://drive.google.com/drive/folders/1-5LzDVEcFKUveakp85x_fLaWxDDYD9qu',
  books: 'https://drive.google.com/drive/folders/1W_cnwUl-6CZdHgjrDKdDwSUsn6pA_GvX',
  lawyers: 'https://drive.google.com/drive/folders/1XesTSYKvvta_5YaDiU6KwoO9SZ3wBGzu',
  whatsapp1: 'https://chat.whatsapp.com/Ecxykn1FMMGEJrWlZac7E1',
  whatsapp2: 'https://chat.whatsapp.com/JojMVaAFBiR5AM6mhyggiX',
  signal: 'https://signal.group/#CjQKIPngT272CSSoQ5VP_ghGfAw21Uheip0rtaDq6MDcLfjuEhBEW7N369y5I40cLJSy_7mq',
};

const nav = [
  ['Home','/'], ['Create a will','/will-creation/'], ['Templates','/will-templates/'],
  ['Seminars','/seminars/'], ['FAQ','/faq/'], ['Lawyers & scholars','/lawyers/'], ['Our team','/team/']
];
const external = (href, label, cls = '') => `<a class="${cls}" href="${href}" target="_blank" rel="noopener noreferrer">${label}<span class="sr-only"> (opens in a new tab)</span></a>`;
const button = (href,label,secondary=false) => `<a class="button ${secondary?'button-secondary':''}" href="${href}">${label}<span aria-hidden="true"> ↗</span></a>`;
const extButton = (href,label,secondary=false) => external(href,`${label}<span aria-hidden="true"> ↗</span>`,`button ${secondary?'button-secondary':''}`);
const eyebrow = t => `<p class="eyebrow">${t}</p>`;
const intro = (k,title,lead) => `<section class="page-hero container">${eyebrow(k)}<h1>${title}</h1><p class="lead">${lead}</p></section>`;
const card = (k,title,body,link='') => `<article class="card">${eyebrow(k)}<h3>${title}</h3><p>${body}</p>${link}</article>`;
const resource = (type,title,detail,href) => `<li class="resource"><div><small>${type}</small><strong>${title}</strong><span>${detail}</span></div>${external(href,'Open resource <span aria-hidden="true">↗</span>','text-link')}</li>`;
const disclaimer = `<aside class="note" aria-label="Disclaimer"><strong>About this resource</strong><p>Islamic Will Canada is a volunteer-driven, non-profit initiative. It is not a lawyer service or legal forum and does not promote any law firm.</p></aside>`;

const pages = [
  {
    slug:'', title:'Islamic Will Canada | Free volunteer-led will resources', description:'Explore free Islamic will templates, a practical creation guide, seminar recordings and community resources from Islamic Will Canada.',
    body:`<section class="home-hero"><div class="container hero-grid"><div>${eyebrow('Free · volunteer-led · Canada')}<h1>Prepare your Islamic will with clarity.</h1><p class="lead">Islamic Will Canada shares free templates, seminars, lawyer information and one-to-one community guidance to help people write an Islamic will.</p><div class="actions">${button('/will-creation/','See the steps')}${button('/will-templates/','Explore templates',true)}</div><p class="hero-small">A community initiative promoting awareness of the Sunnah. Not a lawyer service.</p></div><div class="hero-art" aria-hidden="true"><div class="art-frame"><span class="art-line"></span><span class="art-crescent">☪</span><span class="art-text">A thoughtful step<br>for those you love.</span></div></div></div></section>
    <section class="section container split"><div>${eyebrow('Why it matters')}<h2>Put your wishes in writing.</h2><p>The source site highlights possible difficulties for a family when someone dies without an Islamic will: children’s custody questions, estate distribution under Canadian law, family conflict, missing funeral instructions, health administration decisions, and a longer, more stressful process.</p><p>Its motivation is rooted in the Hadith cited on the original site:</p></div><blockquote><p>“It is not permissible for any Muslim who has something to will, to stay for two nights without having his last will and testament written and kept ready with him.”</p><p lang="ur" dir="rtl">رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: کسی مسلمان کے لیے جن کے پاس وصیت کے قابل کوئی بھی مال ہو درست نہیں کہ دو رات بھی وصیت کو لکھ کر اپنے پاس محفوظ رکھے بغیر گزارے۔</p><cite>Bukhari 2738, as cited by Islamic Will Canada</cite></blockquote></section>
    <section class="section section-tint"><div class="container">${eyebrow('A clear path')}<div class="section-heading"><h2>How to make a simple Islamic will</h2><p>Follow the original five-step method, with the supporting material close at hand.</p></div><ol class="step-grid"><li><span>01</span><h3>Choose a template</h3><p>Browse templates from Ontario masajid. The original site recommends the Windsor Masjid template for its ease of use.</p></li><li><span>02</span><h3>Choose people</h3><p>Identify two witnesses, two executors, and guardians for minor children where applicable.</p></li><li><span>03</span><h3>Sign</h3><p>Have the will signed by you and the witnesses.</p></li><li><span>04</span><h3>Share copies</h3><p>Give signed copies to executors, heirs and others as appropriate.</p></li><li><span>05</span><h3>Keep it ready</h3><p>The original guide considers the process complete after the signed copies are shared.</p></li></ol><div class="actions">${button('/will-creation/','Read the full guide')}</div></div></section>
    <section class="section container">${eyebrow('Explore the resources')}<h2>Practical help, in one place.</h2><div class="card-grid">${card('01','Will templates','Access the Ontario masajid template collection and the recommended Windsor Masjid document.',`<a class="text-link" href="/will-templates/">View templates →</a>`)}${card('02','Recorded learning','Watch the Urdu and English seminars and the hands-on walkthrough of the Windsor template.',`<a class="text-link" href="/seminars/">View seminars →</a>`)}${card('03','Questions & support','Find the original FAQ, resource links and ways to contact the volunteer team.',`<a class="text-link" href="/faq/">Read the FAQ →</a>`)}</div></section><section class="cta-band"><div class="container cta-grid"><div>${eyebrow('Ready to begin?')}<h2>Start with the template and the steps.</h2><p>The resources are free and shared by a volunteer-led initiative.</p></div>${button('/will-creation/','Create a will')}</div></section>`
  },
  {
    slug:'will-creation', title:'How to Create a Simple Islamic Will | Islamic Will Canada', description:'Follow Islamic Will Canada’s original steps: choose a template, select witnesses and executors, sign and share copies.',
    body:`${intro('Practical guide','How to create a simple Islamic will','The five steps below follow the original site’s method. Use the linked template and workshop when working through them.')}
    <section class="section container narrow"><ol class="guide-steps"><li><span class="step-num">01</span><div><h2>Get a template</h2><p>Review the Islamic will templates provided by Ontario masajid. Islamic Will Canada recommends the Windsor Masjid template because it is easy to follow.</p>${extButton(links.windsor,'Open the Windsor template')}${extButton(links.templateFolder,'Browse all templates',true)}</div></li><li><span class="step-num">02</span><div><h2>Choose witnesses, executors and guardians</h2><div class="detail-grid"><div><h3>Two witnesses</h3><p>Ideally they live in the same city or country. The original guidance says they <strong>must not be heirs (waris)</strong>.</p></div><div><h3>Two executors</h3><p>They carry out the will’s instructions. Ideally they live in the same city or country; they may be heirs.</p></div><div><h3>Guardians</h3><p>Identify guardians for minor children, locally or internationally, if applicable.</p></div></div></div></li><li><span class="step-num">03</span><div><h2>Sign the will</h2><p>Have it signed by you and your witnesses.</p></div></li><li><span class="step-num">04</span><div><h2>Share signed copies</h2><p>Give signed copies to your executors, heirs and others as appropriate.</p></div></li><li><span class="step-num">05</span><div><h2>Keep it ready</h2><p>The source describes the process as done after the signed copies are shared.</p></div></li></ol><aside class="note"><strong>Note from the original guide</strong><p>It says notarization by a lawyer is not mandatory, but is highly recommended. The site is not a legal forum; consult a qualified professional for advice about your circumstances.</p></aside></section>
    <section class="section section-tint"><div class="container split"><div>${eyebrow('Walk through it')}<h2>Learn with the hands-on workshop.</h2><p>The December 26, 2021 workshop walks through the Windsor template and uses a filled example. Its live Q&amp;A was answered by barrister Zeeba Ahsan.</p><div class="actions">${extButton(links.workshop,'Watch workshop')}${extButton(links.filled,'View filled example',true)}</div></div><div class="card"><small>Supporting documents</small><ul class="link-list"><li>${external(links.windsor,'Blank Windsor template')}</li><li>${external(links.filled,'Filled Windsor example')}</li><li>${external(links.lawyerAnswers,'Lawyer Q&amp;A response document')}</li></ul></div></div></section>${disclaimer}`
  },
  {
    slug:'will-templates', title:'Islamic Will Templates | Islamic Will Canada', description:'Access the Ontario masajid template collection, the recommended Windsor Masjid template and a filled example.',
    body:`${intro('Documents','Islamic will templates','The original site collects templates produced by various Ontario masajid and recommends the Windsor Masjid template as easy to follow.')}
    <section class="section container narrow"><ul class="resource-list">${resource('Collection','Ontario masajid templates','The template folder linked from the source site.',links.templateFolder)}${resource('DOCX','Islamic Will_Windsor.docx','The blank template recommended by the original guide.',links.windsor)}${resource('DOCX','Filled Template – Last Will_Windsor Islamic.docx','A filled example used with the hands-on workshop.',links.filled)}${resource('DOCX','Q&A for Lawyer-Response by ZA Law.docx','Lawyer responses linked alongside the workshop.',links.lawyerAnswers)}</ul><div class="actions">${button('/will-creation/','Read the creation steps')}</div></section>${disclaimer}`
  },
  {
    slug:'seminars', title:'Seminars & Workshop Recordings | Islamic Will Canada', description:'Watch Islamic Will Canada’s 2021 Urdu and English seminars and its hands-on Islamic will template workshop.',
    body:`${intro('Recorded learning','Seminars & workshop','Watch the original recordings and open their companion materials. Dates and descriptions below are from the source site.')}
    <section class="section container"><div class="seminar-grid">${card('Recording 01 · Urdu','How to make a simple Islamic will','Saturday, February 20, 2021 · 2:00–4:00 PM · Rajab 8, 1442H',`${extButton(links.seminarUrdu,'Watch recording')}${external(links.slidesUrdu,'Open seminar PDF','text-link')}`)}${card('Recording 02 · English','How to make a simple Islamic will','Sunday, July 25, 2021 · Dhul Hijjah 15, 1442H',`${extButton(links.seminarEnglish,'Watch recording')}${external(links.slidesEnglish,'Open seminar PDF','text-link')}`)}${card('Recording 03 · workshop','Hands-on Windsor template walkthrough','Sunday, December 26, 2021 · Jumada Al-Awwal 22, 1443H. Includes a filled template and live Q&amp;A answered by barrister Zeeba Ahsan.',`${extButton(links.workshop,'Watch recording')}${external(links.workshopFolder,'Open workshop folder','text-link')}`)}</div><div class="section-heading extra-space"><h2>Workshop documents</h2><p>Follow along with the blank and filled templates and the lawyer response document.</p></div><ul class="resource-list">${resource('DOCX','Blank Windsor template','The original template.',links.windsor)}${resource('DOCX','Filled Windsor example','Sample completed document.',links.filled)}${resource('DOCX','Lawyer Q&A response','Responses by ZA Law.',links.lawyerAnswers)}${resource('Collection','Other recordings and knowledge base','Additional resources linked from the original site.',links.knowledge)}</ul></div>${disclaimer}`
  },
  {
    slug:'faq', title:'Frequently Asked Questions | Islamic Will Canada', description:'Find the source site’s answers on templates, books, lawyers, funeral services, inheritance calculators and writing a will.',
    body:`${intro('Common questions','Frequently asked questions','These answers reorganize the original site’s first-draft FAQ while keeping its claims and linked resources visible.')}
    <section class="section container narrow faq-list"><details><summary>Where can I get an Islamic will template?</summary><div><p>The source site collects templates produced by various Ontario masajid and recommends the Windsor Masjid template for a simple will.</p>${extButton(links.templateFolder,'Browse templates')}</div></details><details><summary>Are there books on Islamic wills?</summary><div><p>The source links to a folder of books on Islamic wills.</p>${extButton(links.books,'Open books folder')}</div></details><details><summary>Can you recommend a lawyer?</summary><div><p>Islamic Will Canada says it does not market or take commission from any lawyer. It shares names it is familiar with; some lawyers volunteer to answer questions in its WhatsApp groups.</p><p>See the directory and the source’s linked folder.</p><div class="actions">${button('/lawyers/','View directory')}${extButton(links.lawyers,'Open original list',true)}</div></div></details><details><summary>Is there a funeral support service?</summary><div><p>The original FAQ points to ${external('https://fsso.ca/','Funeral Support Services of Ontario (FSSO)')}. It states a one-time family membership payment of <strong>$150</strong> covers a husband, wife and minor children, with a shared cost if a member dies that it says generally does not exceed <strong>$10</strong>. These are the source site’s figures; confirm current terms directly with FSSO before relying on them.</p></div></details><details><summary>Are there Islamic inheritance calculators?</summary><div><p>The original FAQ lists these external resources:</p><ul class="link-list"><li>${external('https://www.inheritancecalculator.net/','inheritancecalculator.net')}</li><li>${external('https://www.inheritance-calculator.com/islamic-inheritance-calculator.php','inheritance-calculator.com')}</li><li>${external('https://www.lubnaa.com/money/InheritCalc-Return.php','lubnaa.com')}</li><li>${external('https://sailanmuslim.com/inheritance-2/inheritance-according-to-islamic-sharia-law/','sailanmuslim.com')}</li><li>miraas-in-islam.com/english/Massail.aspx — the original link is currently unavailable; see the content audit in the repository.</li></ul></div></details><details><summary>What if I die in Canada without an Islamic will?</summary><div><p>The original FAQ lists possible consequences: complications around children’s custody; estate distribution according to Canadian law rather than the intended Islamic distribution; conflict among family members over shares; absent funeral instructions; health administration decisions; and additional stress, frustration or delay for family.</p><p>It also raises a religious concern about an un-Islamic distribution and quotes the Hadith cited on the home page (Bukhari 2738) as a reason not to delay. These are the original site’s concerns, not a prediction for every estate.</p></div></details></section>${disclaimer}`
  },
  {
    slug:'lawyers', title:'Lawyers & Scholars Directory | Islamic Will Canada', description:'View the lawyers and scholars named by the original Islamic Will Canada site, with its non-endorsement notice.',
    body:`${intro('Community directory','Lawyers & scholars','The original site shares names it is familiar with. It says it does not promote, market or take commission from any lawyer. These details were contained in an image on the source page.')}
    <section class="section container"><div class="note"><strong>Verify before contacting</strong><p>This directory reproduces the source site’s contact details. They may have changed. Check a person’s current role, practice and details directly before relying on them.</p></div><div class="directory-grid">
    ${directory('Malik Muhammad Suliman','Ameer Law','Toronto · 506–10 Milner Business Court, M1B 3C6','647-894-5104','malik@ameerlaw.com','https://www.ameerlaw.com')}
    ${directory('Zeeba Ahsan','ZA Law','Toronto · 206–100 McLevin Ave, M1B 5K1','647-687-9529','zahsan@zalaws.com','https://www.zalaws.com')}
    ${directory('Qasim Ali BSc, JD/JD','Nihang Law','Toronto · 302–3300 McNicoll Ave, M1V 5J6','416-321-0353','qasim@nihanglaw.ca','https://www.nihanglaw.ca')}
    ${directory('Sabahah Akbar','Trigil Law','','416-845-3969','sab@trigil.ca','')}
    ${directory('Muezzin Qureshi','KM Law','Toronto · 2–1871 O’Connor Drive, M4A 1X1','416-755-2622','muezzin@kmlawpc.ca','https://www.kmlawpc.ca')}
    ${directory('Mustafa Jilani','KSM Law','London, ON · 156 Oxford St W','519-601-5080','info@kuttyjilani.com','https://www.kuttyjilani.com')}
    ${directory('Sheikh Yūsuf Badāt','Imam, Islamic Foundation of Toronto','','416-402-8542','','https://www.mathabah.org')}
    ${directory('Umer Ramzan','','Ottawa · 1915 Baseline Road, Suite 301','613-263-3456','umer@ramzanlaw.com','https://www.ramzanlaw.com')}
    ${directory('Imam Ismail Ughar','','','','','https://www.bridgehumanity.com')}
    ${directory('Shahzad F. Siddiqui','Abrahams LLP','','416-291-6786','shahzad@abrahamsllp.com','')}
    </div><div class="actions">${extButton(links.lawyers,'Open the original folder')}</div></section>${disclaimer}`
  },
  {
    slug:'team', title:'Our Volunteer Team & Contact | Islamic Will Canada', description:'Meet the Islamic Will Canada volunteer team and find its email, WhatsApp and Signal community links.',
    body:`${intro('About the initiative','A volunteer-led community effort','Islamic Will Canada began as a WhatsApp group in 2020 to raise awareness of writing Islamic wills. The source describes the initiative as 100% volunteer-run and non-profit.')}
    <section class="section container split"><div><h2>What we do</h2><p>The team promotes the Sunnah of writing a free Islamic will, shares knowledge and resources, motivates the community, and offers one-to-one help. It has held seminars with scholars and qualified lawyers. The original site says its WhatsApp groups have 500+ members.</p><p>Its volunteers are community professionals who aim to connect people with scholars and lawyers. They are not themselves a lawyer service.</p></div><div class="card"><small>Our mission</small><ol class="mission-list"><li>Promote awareness of writing a free Islamic will.</li><li>Share templates, seminars and lawyer information.</li><li>Serve through a 100% free, volunteer-driven initiative.</li></ol></div></section><section class="section section-tint"><div class="container">${eyebrow('The volunteers')}<h2>Meet the team</h2><div class="team-grid">${person('haamed','Haamed Pasha Siddiqui Habibi','IT consultant')}${person('mohammad','Mohammad Shabbir','Accounting professional')}${person('jibran','Jibran Aziz','Project manager')}${person('adnan','Adnan Badar','IT consultant')}</div></div></section><section class="section container narrow" id="contact">${eyebrow('Get in touch')}<h2>Contact or volunteer</h2><p>Contact the admin by email, or join one of the community groups linked on the original site.</p><div class="contact-grid"><div class="card"><small>Email</small><h3>Contact admin</h3><p><a href="mailto:islamicwillcanada@gmail.com">islamicwillcanada@gmail.com</a></p></div><div class="card"><small>Community</small><h3>WhatsApp & Signal</h3><ul class="link-list"><li>${external(links.whatsapp1,'WhatsApp group 1')}</li><li>${external(links.whatsapp2,'WhatsApp group 2')}</li><li>${external(links.signal,'Signal group')}</li></ul></div></div></section>${disclaimer}`
  }
];

function directory(name,org,place,tel,email,site){return `<article class="directory-card"><h2>${name}</h2>${org?`<p class="dir-org">${org}</p>`:''}${place?`<p>${place}</p>`:''}<ul>${tel?`<li><a href="tel:${tel.replaceAll('-','')}">${tel}</a></li>`:''}${email?`<li><a href="mailto:${email}">${email}</a></li>`:''}${site?`<li>${external(site,site.replace(/^https?:\/\/www\./,''))}</li>`:''}</ul></article>`}
function person(file,name,role){return `<article class="person"><img src="/assets/${file}.webp" alt="Portrait of ${name}" width="320" height="320" loading="lazy"><h3>${name}</h3><p>${role}</p></article>`}
function shell(page){const url = `${base}/${page.slug ? page.slug+'/' : ''}`;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.description}"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:site_name" content="Islamic Will Canada"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${url}"><meta property="og:image" content="${base}/assets/social-card.svg"><meta name="theme-color" content="#123e38"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script></head><body><a class="skip-link" href="#main">Skip to main content</a><header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Islamic Will Canada home"><span class="brand-mark" aria-hidden="true">✦</span><span>Islamic Will <small>Canada</small></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav">Menu <span aria-hidden="true">☰</span></button><nav class="primary-nav" id="primary-nav" aria-label="Primary navigation">${nav.map(([label,href])=>`<a href="${href}" ${href===`/${page.slug ? page.slug+'/' : ''}`?'aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header><main id="main">${page.body}</main><footer class="site-footer"><div class="container footer-grid"><div><a class="brand footer-brand" href="/"><span class="brand-mark" aria-hidden="true">✦</span><span>Islamic Will <small>Canada</small></span></a><p>Free Islamic will resources shared by a volunteer-led, non-profit community initiative.</p></div><div><h2>Explore</h2>${nav.slice(1).map(([label,href])=>`<a href="${href}">${label}</a>`).join('')}</div><div><h2>Connect</h2><a href="mailto:islamicwillcanada@gmail.com">islamicwillcanada@gmail.com</a><a href="/team/#contact">Contact & volunteer</a><p>Not a lawyer service or legal forum. No law firm is promoted by this site.</p></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Islamic Will Canada</span><span>Information adapted from the original Islamic Will Canada site.</span></div></footer></body></html>`}

fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync('public',out,{recursive:true});
for(const page of pages){const dir=path.join(out,page.slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),shell(page));}
fs.writeFileSync(path.join(out,'404.html'),shell({slug:'404',title:'Page not found | Islamic Will Canada',description:'The page you requested could not be found.',body:`<section class="page-hero container error-page">${eyebrow('404 · Page not found')}<h1>That page is not here.</h1><p class="lead">Return to the homepage or explore the resources from the navigation.</p>${button('/','Go to homepage')}</section>`}));
fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${base}/${p.slug?p.slug+'/':''}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${pages.length} pages plus 404 in ${out}`);
